### ISSUE TITLE
utf8-problem when installing on Raspberry Pi

### ISSUE THREAD

**Issue by ekstroem** [SoCo/socos#56]
Howdy,

Not sure about the exact dependencies but if I install `socos` on my raspberry Pi then I run into the same problems with (lack of) utf8 specification as described and fixed [in issue #312 here](https://github.com/SoCo/SoCo/issues/312).

Maybe that will propate automatically from SoCo when socos is repackaged but right now the command

```
sudo pip-3.2 install git+https://github.com/SoCo/socos
```

fails.

(This was more of a notification than a real error - just wanted make sure it was mentioned if the install scripts are separate).

**Comment by KennethNielsen** [comment]
Hallo @ekstroem. 

Well. SoCos depends on an older version of SoCo (version 0.8 if I remember) that will surely have the bug that we just fixed for 0.11.1. There is current active work #55 to get SoCos updated to target the newest version in which case this would be automatically fixed. Given that work is already ongoing for this, I think it is better to wait for the new version.

That being said. The setup.py file for SoCos may be (and probably is) affected by the same kind of problem. So we should look into that. @stefankoegl How did you get a python 3.2 to test on?

**Comment by stefankoegl** [comment]
@ekstroem can you please paste the full error message? I'm not sure where the issue is this time.

I've opened #57 to discuss the next release.

**Comment by ekstroem** [comment]
@stefankoegl Sure. It is

```
pi@pip ~ $ sudo pip-3.2 install git+https://github.com/SoCo/socos
Downloading/unpacking git+https://github.com/SoCo/socos
  Cloning https://github.com/SoCo/socos to /tmp/pip-vep_xq-build
  Running setup.py egg_info for package from git+https://github.com/SoCo/socos
    
Downloading/unpacking soco==0.8 (from socos==0.1)
  Downloading soco-0.8.tar.gz (67Kb): 67Kb downloaded
  Running setup.py egg_info for package soco
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/build/soco/setup.py", line 63, in <module>
        LONG_DESCRIPTION = file.read()
      File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3716: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/soco/setup.py", line 63, in <module>

    LONG_DESCRIPTION = file.read()

  File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3716: ordinal not in range(128)

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/soco
Storing complete log in /root/.pip/pip.log
```

Let me know if I can do anything else to help out

**Comment by stefankoegl** [comment]
Ah, I see... this should automatically be fixed as soon as ``socos`` depends on SoCo 0.11.1. This should be completed soon as part of #55.

**Comment by ekstroem** [comment]
Perfect - no need to tinker with anything socos-specific then. I'll close this

**Comment by stefankoegl** [comment]
@ekstroem, for now you should be able to install socos with

    pip install git+https://github.com/petteraas/socos.git@update_soco#egg=socos-dev

**Comment by ekstroem** [comment]
@stefankoegl Hmm ... nope. That gives the exact same error as above except it references soco 0.11.1

**Comment by stefankoegl** [comment]
That's strange... are you sure everything else is exactly the same? Can you please post the new output?

**Comment by ekstroem** [comment]
Just tried it again (on the same machine):

```
pi@pip ~ $ sudo pip-3.2 install git+https://github.com/petteraas/socos.git@update_soco#egg=socos-dev
Downloading/unpacking socos-dev from git+https://github.com/petteraas/socos.git@update_soco
  Running setup.py egg_info for package socos-dev
    
Downloading/unpacking soco==0.11.1 (from socos-dev)
  Running setup.py egg_info for package soco
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/build/soco/setup.py", line 63, in <module>
        LONG_DESCRIPTION = file.read()
      File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3716: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/soco/setup.py", line 63, in <module>

    LONG_DESCRIPTION = file.read()

  File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3716: ordinal not in range(128)

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/soco
Storing complete log in /root/.pip/pip.log
```

**Comment by stefankoegl** [comment]
That's strange... What happens if you run the following?

    sudo pip-3.2 install soco==0.11.1
    sudo pip-3.2 install git+https://github.com/petteraas/socos.git@update_soco#egg=socos-dev

**Comment by ekstroem** [comment]
Fails on the first command
```
pi@pip ~ $ sudo pip-3.2 install soco==0.11.1
Downloading/unpacking soco==0.11.1
  Running setup.py egg_info for package soco
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/pi/build/soco/setup.py", line 63, in <module>
        LONG_DESCRIPTION = file.read()
      File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3716: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/pi/build/soco/setup.py", line 63, in <module>

    LONG_DESCRIPTION = file.read()

  File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3716: ordinal not in range(128)

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/pi/build/soco
Storing complete log in /root/.pip/pip.log
```

**Comment by stefankoegl** [comment]
Are you still able to reproduce this error? It somehow seems that pip is fetching the wrong file for you...

It's failing in line 63 of ``setup.py`` which - in version 0.11.1 - is not the one shown in the description

https://github.com/SoCo/SoCo/blob/v0.11.1/setup.py#L63

Can you please try again and let me know your results?
