### ISSUE TITLE
Crash on partymode

### ISSUE THREAD

**Issue by polyzen** [SoCo/socos#80]
```
~/p/repo > socos                                                                 
socos> list
(1) 192.168.1.19    Living Room
(2) 192.168.1.21    Bedroom
socos> partymode
Traceback (most recent call last):
  File "/usr/bin/socos", line 11, in <module>
    load_entry_point('socos==0.2', 'console_scripts', 'socos')()
  File "/usr/lib/python3.7/site-packages/socos/runner.py", line 24, in main
    socos.shell()
  File "/usr/lib/python3.7/site-packages/socos/core.py", line 246, in shell
    self.process_cmd(args)
  File "/usr/lib/python3.7/site-packages/socos/core.py", line 155, in process_cmd
    result = func(*args)
  File "/usr/lib/python3.7/site-packages/socos/core.py", line 328, in partymode
    self.current_speaker.partymode()
AttributeError: 'NoneType' object has no attribute 'partymode'
```

**Comment by polyzen** [comment]
This happens if you forget to select a speaker.
